export const USER_PATH = 'USER_PATH'

export const Events = {
  OPEN_EDITOR: 'OPEN_EDITOR',
  CREATE_PROJECT: 'CREATE_PROJECT',
  GET_INIT_FOLDER: 'GET_INIT_FOLDER',
  GET_PROJECT_LIST: 'GET_PROJECT_LIST',
  CONFIGURE_PROJECT: 'CONFIGURE_PROJECT',
}
